2022-05-19 17:03:04,159 INFO    MainThread:10012 [wandb_setup.py:_flush():75] Loading settings from /home/hikari007/.config/wandb/settings
2022-05-19 17:03:04,159 INFO    MainThread:10012 [wandb_setup.py:_flush():75] Loading settings from /home/hikari007/dl-torch/Classification/VGGNet/wandb/settings
2022-05-19 17:03:04,159 INFO    MainThread:10012 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-05-19 17:03:04,159 INFO    MainThread:10012 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'Classification/VGGNet/train.py', 'program': '/home/hikari007/dl-torch/Classification/VGGNet/train.py'}
2022-05-19 17:03:04,160 INFO    MainThread:10012 [wandb_init.py:_log_setup():437] Logging user logs to /home/hikari007/dl-torch/Classification/VGGNet/wandb/run-20220519_170304-188kmhvw/logs/debug.log
2022-05-19 17:03:04,160 INFO    MainThread:10012 [wandb_init.py:_log_setup():438] Logging internal logs to /home/hikari007/dl-torch/Classification/VGGNet/wandb/run-20220519_170304-188kmhvw/logs/debug-internal.log
2022-05-19 17:03:04,160 INFO    MainThread:10012 [wandb_init.py:init():471] calling init triggers
2022-05-19 17:03:04,160 INFO    MainThread:10012 [wandb_init.py:init():474] wandb.init called with sweep_config: {}
config: {'batch_size': 8, 'num_workers': 8, 'epochs': 10, 'model': 'vgg16', 'save_path': './save_weights'}
2022-05-19 17:03:04,160 INFO    MainThread:10012 [wandb_init.py:init():524] starting backend
2022-05-19 17:03:04,160 INFO    MainThread:10012 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-05-19 17:03:04,179 INFO    MainThread:10012 [backend.py:ensure_launched():217] starting backend process...
2022-05-19 17:03:04,183 INFO    MainThread:10012 [backend.py:ensure_launched():222] started backend process with pid: 10068
2022-05-19 17:03:04,184 INFO    MainThread:10012 [wandb_init.py:init():533] backend started and connected
2022-05-19 17:03:04,186 INFO    MainThread:10012 [wandb_init.py:init():597] updated telemetry
2022-05-19 17:03:04,196 INFO    MainThread:10012 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-05-19 17:03:09,471 WARNING MainThread:10012 [wandb_init.py:init():1016] interrupted
Traceback (most recent call last):
  File "/home/hikari007/miniconda3/envs/d2l/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 995, in init
    run = wi.init()
  File "/home/hikari007/miniconda3/envs/d2l/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 629, in init
    run_result = backend.interface.communicate_run(run, timeout=30)
  File "/home/hikari007/miniconda3/envs/d2l/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/hikari007/miniconda3/envs/d2l/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 324, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/hikari007/miniconda3/envs/d2l/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/hikari007/miniconda3/envs/d2l/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/hikari007/miniconda3/envs/d2l/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/hikari007/miniconda3/envs/d2l/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
